name: 'godot-export-version'
description: 'Set project version in and export presets'
inputs:
  version:  # id of input
    description: 'project version'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Exports Override
      shell: bash
      env:
        VALUE: ${{ inputs.version }}
        EXPORT_NAMES: |-
          application/version
          application/short_version
          application/file_version
          application/product_version
      run: |-
        echo "${EXPORT_NAMES}" | while read name 0:.
        J?NOj'
          Description:
          Type: List<AWS::Route53::HostedZone::Id>
          Default:
        do
          sed -i.bak 's|'"${name}"'=.*|'"${name}"'="'"${VALUE}"'"|g' export_presets.cfg
        done

        echo "-- export_presets.cfg --"
        grep version export_presets.cfg